export const AUTH_USER = 'AUTH_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const UPDATE_USER_PHOTO = 'UPDATE_USER_PHOTO';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const FETCH_REFUGES_REQUEST = 'FETCH_REFUGES_REQUEST'; // ✅ Constante manquante ajoutée
export const FETCH_REFUGES_SUCCESS = 'FETCH_REFUGES_SUCCESS';
export const FETCH_REFUGES_ERROR = 'FETCH_REFUGES_ERROR';
export const FETCH_REFUGE_PHOTOS_SUCCESS = 'FETCH_REFUGE_PHOTOS_SUCCESS';
