"""Table

Revision ID: 2740bd83fc51
Revises: 54701d0a09ac
Create Date: 2025-01-31 04:14:32.107886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2740bd83fc51'
down_revision: Union[str, None] = '54701d0a09ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alert_visuelle_idAlertVisuelle', table_name='alert_visuelle')
    op.drop_table('alert_visuelle')
    op.drop_index('ix_alert_vibrante_idAlertVibrante', table_name='alert_vibrante')
    op.drop_table('alert_vibrante')
    op.drop_constraint('itineraire_userID_fkey', 'itineraire', type_='foreignkey')
    op.drop_column('itineraire', 'userID')
    op.alter_column('itineraire_manager', 'idUser',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('itineraire_manager', 'idItineraire',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_itineraire_manager_idManager', table_name='itineraire_manager')
    op.drop_column('itineraire_manager', 'idManager')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itineraire_manager', sa.Column('idManager', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_itineraire_manager_idManager', 'itineraire_manager', ['idManager'], unique=False)
    op.alter_column('itineraire_manager', 'idItineraire',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('itineraire_manager', 'idUser',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('itineraire', sa.Column('userID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('itineraire_userID_fkey', 'itineraire', 'user', ['userID'], ['userID'], ondelete='CASCADE')
    op.create_table('alert_vibrante',
    sa.Column('idAlertVibrante', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dateVibrante', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('intensite', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('userID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['user.userID'], name='alert_vibrante_userID_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idAlertVibrante', name='alert_vibrante_pkey')
    )
    op.create_index('ix_alert_vibrante_idAlertVibrante', 'alert_vibrante', ['idAlertVibrante'], unique=False)
    op.create_table('alert_visuelle',
    sa.Column('idAlertVisuelle', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dateVisuelle', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('userID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['user.userID'], name='alert_visuelle_userID_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idAlertVisuelle', name='alert_visuelle_pkey')
    )
    op.create_index('ix_alert_visuelle_idAlertVisuelle', 'alert_visuelle', ['idAlertVisuelle'], unique=False)
    # ### end Alembic commands ###
